version: "4.2"
services:
  db:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_URL: ${KC_HOSTNAME_URL}
      KC_HOSTNAME_ADMIN_URL: ${KC_HOSTNAME_ADMIN_URL}
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH}
      KC_HTTP_ENABLED: ${KC_HTTP_ENABLED}
      KC_LOG_LEVEL: ${KC_LOG_LEVEL}
      KC_LOG_CONSOLE_OUTPUT: ${KC_LOG_CONSOLE_OUTPUT}
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/themes/task-management:/opt/keycloak/themes/task-management
      - keycloak-data:/opt/keycloak/data/
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8080/auth/realms/master"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    environment:
      REALM_PUBLIC_KEY: ${REALM_PUBLIC_KEY}
      SECRET_KEY: ${SECRET_KEY}
      CLIENT_ID: ${CLIENT_ID}
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5000/api/v1/"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  keycloak-data:
