version: "4.2"
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      KC_HOST_URL: http://localhost/auth
      KEYCLOAK_THEME_CACHE: 'false'
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/themes/task-management:/opt/jboss/keycloak/themes/task-management
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8080/auth/realms/master"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
